const $=id=>document.getElementById(id);
const STORAGE_KEY="focusCurveV2Data",SETTINGS_KEY="focusCurveV2Settings";
let data=loadJSON(STORAGE_KEY,{ratings:[],cycles:[]}),settings=loadJSON(SETTINGS_KEY,{theme:"dark"});
let phase="focus",running=false,timerId=null,selectedScore=null,totalSeconds=5400,remainingSeconds=5400,elapsedSeconds=0,lastCheckMinute=0,sessionStartedAt=null,currentSessionId=null;
const els={timer:$("timer"),subtimer:$("subtimer"),progressBar:$("progressBar"),phaseBadge:$("phaseBadge"),sessionClock:$("sessionClock"),startBtn:$("startBtn"),pauseBtn:$("pauseBtn"),finishBtn:$("finishBtn"),resetBtn:$("resetBtn"),focusMinutes:$("focusMinutes"),breakMinutes:$("breakMinutes"),checkInterval:$("checkInterval"),subject:$("subject"),ratingPrompt:$("ratingPrompt"),ratingButtons:[...document.querySelectorAll("#ratingButtons button")],note:$("note"),saveRatingBtn:$("saveRatingBtn"),sleepHours:$("sleepHours"),sleepQuality:$("sleepQuality"),hunger:$("hunger"),distraction:$("distraction"),history:$("history"),dayChart:$("dayChart"),importFile:$("importFile")};
const svg={x0:58,x1:950,yBase:248,yTop:42};
function loadJSON(k,f){try{const v=localStorage.getItem(k);return v?JSON.parse(v):f}catch{return f}}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(data));localStorage.setItem(SETTINGS_KEY,JSON.stringify(settings));renderAll()}
function focusSeconds(){return Number(els.focusMinutes.value)*60}function breakSeconds(){return Number(els.breakMinutes.value)*60}function phaseDuration(){return phase==="focus"?focusSeconds():breakSeconds()}
function formatTime(s){return `${Math.floor(s/60).toString().padStart(2,"0")}:${(s%60).toString().padStart(2,"0")}`}function today(){return new Date().toISOString().slice(0,10)}function clock(d){return d.toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"})}
function esc(t){return String(t).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}function mean(a){return a.length?a.reduce((x,y)=>x+y,0)/a.length:null}
function ease(t){return t<.5?2*t*t:1-Math.pow(-2*t+2,2)/2}function base(t){if(t<=.28)return .22+.60*ease(t/.28);if(t<=.60)return .86+.10*Math.sin(((t-.28)/.32)*Math.PI);return .86-.62*ease(Math.min(1,(t-.60)/.40))}
function model(){const bins=12,r=data.ratings.filter(x=>x.phase==="focus"&&typeof x.position==="number"),s=Array(bins).fill(0),c=Array(bins).fill(0);r.forEach(x=>{const i=Math.min(bins-1,Math.max(0,Math.floor(x.position*bins)));s[i]+=(Number(x.score)-1)/4;c[i]++});const b=Array.from({length:bins},(_,i)=>base((i+.5)/bins)),a=Math.min(.9,r.length/28),raw=b.map((v,i)=>c[i]?(1-a)*v+a*(s[i]/c[i]):v),v=raw.map((_,i)=>{let q=0,w=0;for(let j=i-1;j<=i+1;j++){if(j<0||j>=bins)continue;const z=j===i?2:1;q+=raw[j]*z;w+=z}return q/w}),mx=Math.max(...v),th=Math.max(mx-.06,mx*.92),p=v.map((x,i)=>({x,i})).filter(o=>o.x>=th).map(o=>o.i),ps=p.length?p[0]:3,pe=p.length?p[p.length-1]:6;return{bins,values:v,total:r.length,peakStart:ps/bins,peakEnd:(pe+1)/bins,confidence:r.length>=24?"Alta":r.length>=10?"Moderada":"Baixa"}}
function level(m,t){const p=t*m.bins,i=Math.min(m.bins-1,Math.max(0,Math.floor(p))),f=p-i,a=m.values[i],b=m.values[Math.min(m.bins-1,i+1)];return a+(b-a)*Math.min(1,Math.max(0,f))}
const x=t=>svg.x0+t*(svg.x1-svg.x0),y=l=>svg.yBase-l*(svg.yBase-svg.yTop);
function renderCurve(){const m=model(),g=$("gridGroup"),band=$("peakBand"),lab=$("labelGroup");g.innerHTML="";band.innerHTML="";lab.innerHTML="";for(let i=0;i<=6;i++){const xx=svg.x0+(i/6)*(svg.x1-svg.x0);g.innerHTML+=`<line x1="${xx}" x2="${xx}" y1="38" y2="248" stroke="#475569" stroke-dasharray="3 6" opacity=".45"/>`}[.25,.5,.75].forEach(r=>{const yy=svg.yBase-r*(svg.yBase-svg.yTop);g.innerHTML+=`<line x1="${svg.x0}" x2="${svg.x1}" y1="${yy}" y2="${yy}" stroke="#475569" stroke-dasharray="3 6" opacity=".45"/>`});const ad=[],rf=[],ar=[];for(let i=0;i<=180;i++){const t=i/180,xx=x(t),yy=y(level(m,t)),yr=y(base(t));ad.push(`${i?"L":"M"} ${xx} ${yy}`);rf.push(`${i?"L":"M"} ${xx} ${yr}`);ar.push(`${xx} ${yy}`)}$("curvePath").setAttribute("d",ad.join(" "));$("referencePath").setAttribute("d",rf.join(" "));$("areaPath").setAttribute("d",`M ${svg.x0} ${svg.yBase} L ${ar.join(" L ")} L ${svg.x1} ${svg.yBase} Z`);const x1=x(m.peakStart),x2=x(m.peakEnd);band.innerHTML=`<rect x="${x1}" y="38" width="${x2-x1}" height="210" rx="16" fill="rgba(134,239,172,.10)" stroke="rgba(134,239,172,.38)"/><line x1="${x1}" x2="${x1}" y1="38" y2="248" stroke="#86efac" stroke-dasharray="5 5"/><line x1="${x2}" x2="${x2}" y1="38" y2="248" stroke="#86efac" stroke-dasharray="5 5"/>`;const fm=Number(els.focusMinutes.value),sm=m.peakStart*fm,em=m.peakEnd*fm;$("peakWindow").textContent=`Pico estimado: ${Math.round(sm)}–${Math.round(em)} min`;[[0,["0 min"],"start"],[m.peakStart,["Pico começa",`${Math.round(sm)} min`],"middle"],[m.peakEnd,["Pico termina",`${Math.round(em)} min`],"middle"],[1,["Fim do foco",`${fm} min`],"end"]].forEach(o=>{const xx=x(o[0]),sp=o[1].map((p,i)=>`<tspan x="${xx}" dy="${i?14:0}">${p}</tspan>`).join("");lab.innerHTML+=`<text x="${xx}" y="276" text-anchor="${o[2]}" fill="#94a3b8" font-size="13">${sp}</text>`});const t=phase==="focus"?Math.min(1,elapsedSeconds/Math.max(1,focusSeconds())):1,cx=x(t),cy=y(level(m,t));$("currentLine").setAttribute("x1",cx);$("currentLine").setAttribute("x2",cx);$("currentDot").setAttribute("cx",cx);$("currentDot").setAttribute("cy",cy);$("statusText").textContent=!running&&elapsedSeconds===0?"Inicie um bloco para acompanhar sua posição na curva.":phase==="break"?"Você está na pausa de recuperação.":t<m.peakStart?"Você ainda está entrando em ritmo.":t<=m.peakEnd?"Você está dentro da sua janela prevista de foco máximo.":"Você já passou da janela prevista de pico.";$("peakClockText").textContent=sessionStartedAt&&phase==="focus"?`${clock(new Date(new Date(sessionStartedAt).getTime()+sm*60000))} até ${clock(new Date(new Date(sessionStartedAt).getTime()+em*60000))}`:"Comece o cronômetro para ver os horários.";$("adaptationText").textContent=`${m.confidence} — ${m.total} avaliações usadas.`}
function renderDay(){const c=els.dayChart,ctx=c.getContext("2d"),dpr=window.devicePixelRatio||1,w=c.clientWidth||900,h=360;c.width=w*dpr;c.height=h*dpr;c.style.height=h+"px";ctx.scale(dpr,dpr);ctx.clearRect(0,0,w,h);const pad={l:48,r:20,t:24,b:42},bk=Array.from({length:24},()=>[]);data.ratings.filter(r=>r.phase==="focus").forEach(r=>bk[new Date(r.timestamp).getHours()].push(Number(r.score)));const av=bk.map(a=>a.length?mean(a):null),cs=getComputedStyle(document.documentElement),mut=cs.getPropertyValue("--muted").trim(),bor=cs.getPropertyValue("--border").trim(),acc=cs.getPropertyValue("--accent").trim();ctx.strokeStyle=bor;ctx.fillStyle=mut;ctx.font="12px system-ui";for(let s=1;s<=5;s++){const yy=pad.t+(5-s)*(h-pad.t-pad.b)/4;ctx.beginPath();ctx.moveTo(pad.l,yy);ctx.lineTo(w-pad.r,yy);ctx.stroke();ctx.fillText(String(s),18,yy+4)}[0,4,8,12,16,20,23].forEach(hr=>{const xx=pad.l+hr*(w-pad.l-pad.r)/23;ctx.fillText(`${String(hr).padStart(2,"0")}h`,xx-10,h-16)});const pts=[];av.forEach((v,hr)=>{if(v===null)return;pts.push({x:pad.l+hr*(w-pad.l-pad.r)/23,y:pad.t+(5-v)*(h-pad.t-pad.b)/4,hr,v})});if(pts.length){ctx.strokeStyle=acc;ctx.lineWidth=3;ctx.beginPath();pts.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.stroke();ctx.fillStyle=acc;pts.forEach(p=>{ctx.beginPath();ctx.arc(p.x,p.y,4,0,Math.PI*2);ctx.fill()});const best=pts.reduce((a,b)=>b.v>a.v?b:a);$("dayInsight").textContent=`Seu melhor desempenho médio aparece por volta de ${String(best.hr).padStart(2,"0")}h, com foco ${best.v.toFixed(1)}/5.`}else $("dayInsight").textContent="Ainda não há dados suficientes para estimar seu melhor horário do dia."}
function renderContext(){const r=data.ratings.filter(x=>x.phase==="focus"),it=[],sl=r.filter(x=>x.sleepHours!=="");if(sl.length>=6){const a=sl.filter(x=>Number(x.sleepHours)>=7).map(x=>Number(x.score)),b=sl.filter(x=>Number(x.sleepHours)<7).map(x=>Number(x.score));if(a.length>=2&&b.length>=2)it.push(`Foco médio com ≥7 h de sono: ${mean(a).toFixed(1)}/5; com <7 h: ${mean(b).toFixed(1)}/5.`)}const ds=r.filter(x=>x.distraction!=="");if(ds.length>=6){const a=ds.filter(x=>Number(x.distraction)<=2).map(x=>Number(x.score)),b=ds.filter(x=>Number(x.distraction)>=4).map(x=>Number(x.score));if(a.length>=2&&b.length>=2)it.push(`Foco médio com poucas distrações: ${mean(a).toFixed(1)}/5; com muitas: ${mean(b).toFixed(1)}/5.`)}$("contextInsights").innerHTML=it.length?it.map(v=>`<div class="insight-item">${esc(v)}</div>`).join(""):'<div class="insight-item">Registre algumas avaliações com contexto para gerar comparações.</div>'}
function renderStats(){const td=today(),cy=data.cycles.filter(c=>c.timestamp.slice(0,10)===td),rt=data.ratings.filter(r=>r.timestamp.slice(0,10)===td);$("ratingsStat").textContent=data.ratings.length;$("cyclesStat").textContent=cy.length;$("avgStat").textContent=rt.length?mean(rt.map(r=>Number(r.score))).toFixed(1):"—";$("minutesStat").textContent=cy.reduce((s,c)=>s+Number(c.completedMinutes||0),0)}
function renderHistory(){const r=[...data.ratings].reverse().slice(0,30);els.history.innerHTML=r.length?r.map(v=>`<div class="history-item"><div><strong>${esc(v.subject||"Sem matéria")}</strong><div><small>${new Date(v.timestamp).toLocaleString("pt-BR",{dateStyle:"short",timeStyle:"short"})} • ${v.elapsedMinutes} min${v.sleepHours!==""?` • ${v.sleepHours} h sono`:""}</small></div>${v.note?`<div><small>${esc(v.note)}</small></div>`:""}</div><div class="score">${v.score}/5</div></div>`).join(""):'<div class="empty">Nenhum registro ainda.</div>'}
function update(){els.timer.textContent=formatTime(remainingSeconds);els.subtimer.textContent=phase==="focus"?"Tempo restante do bloco de foco":"Tempo restante da pausa de recuperação";els.progressBar.style.width=`${Math.min(100,Math.max(0,(totalSeconds-remainingSeconds)/Math.max(1,totalSeconds)*100))}%`;els.phaseBadge.className=phase==="focus"?"phase phase-focus":"phase phase-break";els.phaseBadge.textContent=phase==="focus"?"● Foco":"● Pausa";els.sessionClock.textContent=sessionStartedAt?`Início: ${clock(new Date(sessionStartedAt))}`:"Sessão não iniciada";renderCurve()}
function configure(p){phase=p;totalSeconds=phaseDuration();remainingSeconds=totalSeconds;elapsedSeconds=0;lastCheckMinute=0;selectedScore=null;clearSelection();els.saveRatingBtn.disabled=true;els.ratingPrompt.textContent=phase==="focus"?"Inicie o cronômetro para começar.":"Aproveite sua pausa.";update()}
function start(){if(running)return;running=true;if(!sessionStartedAt)sessionStartedAt=new Date().toISOString();if(!currentSessionId)currentSessionId=crypto.randomUUID?crypto.randomUUID():String(Date.now());els.startBtn.disabled=true;els.pauseBtn.disabled=false;els.finishBtn.disabled=false;els.focusMinutes.disabled=true;els.breakMinutes.disabled=true;els.checkInterval.disabled=true;timerId=setInterval(()=>{if(remainingSeconds>0){remainingSeconds--;elapsedSeconds++;requestMaybe();update()}else complete()},1000)}
function pause(){running=false;clearInterval(timerId);els.startBtn.disabled=false;els.startBtn.textContent="Continuar";els.pauseBtn.disabled=true}
function reset(){clearInterval(timerId);running=false;sessionStartedAt=null;currentSessionId=null;els.startBtn.disabled=false;els.startBtn.textContent="Iniciar";els.pauseBtn.disabled=true;els.finishBtn.disabled=true;els.focusMinutes.disabled=false;els.breakMinutes.disabled=false;els.checkInterval.disabled=false;configure("focus")}
function requestMaybe(){if(phase!=="focus")return;const m=Math.floor(elapsedSeconds/60),i=Number(els.checkInterval.value);if(m>0&&m%i===0&&m!==lastCheckMinute){lastCheckMinute=m;els.ratingPrompt.textContent=`Como está sua concentração após ${m} minutos?`}}
function clearSelection(){els.ratingButtons.forEach(b=>b.classList.remove("active"))}
els.ratingButtons.forEach(b=>b.addEventListener("click",()=>{selectedScore=Number(b.dataset.score);clearSelection();b.classList.add("active");els.saveRatingBtn.disabled=false}));
function saveRating(){if(selectedScore===null)return;data.ratings.push({id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),timestamp:new Date().toISOString(),subject:els.subject.value.trim()||"Sem matéria",score:selectedScore,note:els.note.value.trim(),elapsedMinutes:Math.round(elapsedSeconds/60),focusDurationMinutes:Number(els.focusMinutes.value),position:Math.min(1,elapsedSeconds/Math.max(1,focusSeconds())),sessionId:currentSessionId,phase,sleepHours:els.sleepHours.value,sleepQuality:els.sleepQuality.value,hunger:els.hunger.value,distraction:els.distraction.value});selectedScore=null;els.note.value="";clearSelection();els.saveRatingBtn.disabled=true;els.ratingPrompt.textContent="Avaliação salva. Continue estudando.";save()}
function complete(){clearInterval(timerId);running=false;if(phase==="focus"){data.cycles.push({id:currentSessionId,timestamp:new Date().toISOString(),subject:els.subject.value.trim()||"Sem matéria",plannedMinutes:Number(els.focusMinutes.value),completedMinutes:Math.max(1,Math.round(elapsedSeconds/60))});save();alert("Bloco de foco concluído. Agora faça sua pausa.");els.startBtn.textContent="Iniciar pausa";configure("break")}else{alert("Pausa concluída.");els.startBtn.textContent="Iniciar";currentSessionId=null;sessionStartedAt=null;configure("focus")}els.startBtn.disabled=false;els.pauseBtn.disabled=true;els.finishBtn.disabled=true;els.focusMinutes.disabled=false;els.breakMinutes.disabled=false;els.checkInterval.disabled=false}
function renderAll(){renderStats();renderHistory();renderCurve();renderDay();renderContext()}
function download(content,name,type){const blob=new Blob([content],{type}),u=URL.createObjectURL(blob),a=document.createElement("a");a.href=u;a.download=name;a.click();URL.revokeObjectURL(u)}
function exportCSV(){if(!data.ratings.length)return alert("Ainda não há avaliações.");const h=["Data","Hora","Materia","MinutoSessao","PosicaoBloco","NotaFoco","SonoHoras","QualidadeSono","Fome","Distracao","Observacao"],rows=data.ratings.map(r=>{const d=new Date(r.timestamp),v=[d.toLocaleDateString("pt-BR"),d.toLocaleTimeString("pt-BR"),r.subject,r.elapsedMinutes,`${Math.round((r.position||0)*100)}%`,r.score,r.sleepHours||"",r.sleepQuality||"",r.hunger||"",r.distraction||"",r.note||""];return v.map(x=>`"${String(x).replace(/"/g,'""')}"`).join(",")});download("\uFEFF"+[h.join(","),...rows].join("\n"),`focus_curve_${today()}.csv`,"text/csv;charset=utf-8")}
function exportJSON(){download(JSON.stringify(data,null,2),`focus_curve_backup_${today()}.json`,"application/json")}
function importJSON(file){const r=new FileReader();r.onload=()=>{try{const p=JSON.parse(r.result);if(!Array.isArray(p.ratings)||!Array.isArray(p.cycles))throw 0;data=p;save();alert("Backup importado.")}catch{alert("JSON inválido.")}};r.readAsText(file)}
function applyTheme(){document.documentElement.dataset.theme=settings.theme==="light"?"light":"dark"}
$("themeBtn").addEventListener("click",()=>{settings.theme=settings.theme==="light"?"dark":"light";applyTheme();save()});els.startBtn.addEventListener("click",start);els.pauseBtn.addEventListener("click",pause);els.finishBtn.addEventListener("click",complete);els.resetBtn.addEventListener("click",reset);els.saveRatingBtn.addEventListener("click",saveRating);els.focusMinutes.addEventListener("change",()=>{if(!running&&phase==="focus")configure("focus");renderAll()});els.breakMinutes.addEventListener("change",()=>{if(!running&&phase==="break")configure("break");renderAll()});$("exportCsvBtn").addEventListener("click",exportCSV);$("exportJsonBtn").addEventListener("click",exportJSON);$("importJsonBtn").addEventListener("click",()=>els.importFile.click());els.importFile.addEventListener("change",e=>{const f=e.target.files?.[0];if(f)importJSON(f);e.target.value=""});$("clearBtn").addEventListener("click",()=>{if(confirm("Apagar todo o histórico?")){data={ratings:[],cycles:[]};save();reset()}});window.addEventListener("resize",renderDay);applyTheme();update();renderAll();